# Generated by Django 4.2.5 on 2023-09-12 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_avatar_user_bio_alter_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('17e649e4-3a9e-4cb2-8515-8f6a6ef53c71'), editable=False, unique=True),
        ),
    ]
